[MIG] academic/: Migration to 13.0
ingadhoc/odoo-academic pull request #55
Opened 2020-09-02 20:02 UTC by nmadhoc

2020-09-16 12:45 UTC, nicomacr requested changes
Hello @nmadhoc 

I left some comments in the code for you to check out.

Bes,

2020-09-16 12:45 UTC, nicomacr commented on academic/security/academic_security.xml
> +
Remove this blank space

2020-09-16 12:45 UTC, nicomacr commented on academic/security/ir.model.access.csv
> +
same as the previous comment

2020-09-16 12:45 UTC, nicomacr commented on academic/views/academic_menuitem.xml
> +
remove this line

2020-09-16 12:45 UTC, nicomacr commented on academic/views/res_partner_views.xml
> +
remove line

2020-09-16 12:45 UTC, nicomacr commented on oca_dependencies.txt
> +
remove line

2020-09-16 12:45 UTC, nicomacr commented on academic/demo/res_users_demo.xml
> +        <field name="company_id" ref="base.main_company"/>
why change the company, the old one dosen't exist any more?

2020-09-16 12:45 UTC, nicomacr commented on academic/demo/res_company_demo.xml
> +        <!-- <field name="fiscalyear_last_day">31</field> -->
Apply this line and the lines below:

Why the comment lines?

It's not use, better delete them

2020-09-16 12:45 UTC, nicomacr commented on academic/controllers/website.py
> -from odoo.addons.website.controllers.main import Website
Why delete this file?

It's necessary to redirect portal user to backend

2020-09-16 15:26 UTC, nmadhoc commented
> Hello @nmadhoc
> 
> I left some comments in the code for you to check out.
> 
> Bes,

Thanks so much for the feedback @nicomacr!  
I recently uploaded the changes you requested and the tests are successful.
Take care!

2020-10-14 20:10 UTC, nicomacr approved these changes, later dismissed
Technical Review +1

2021-02-07 09:18 UTC, merged